package com.aci.smart_onboarding.swagger;

import java.util.Set;

public class WalletronRequestAndResponses {

  private WalletronRequestAndResponses() {}

  public static final String WALLETRON_REQUEST_EXAMPLE =
      """
      {
        "brdId": "BRD123",
        "brdName": "Walletron Setup",
        "walletronEnabled": true,
        "siteConfiguration": {
          "features": [
            { "viewValue": "Feature A", "selected": true },
            { "viewValue": "Feature B", "selected": false }
          ],
          "numberOfFields": "3",
          "fields": [
            { "viewValue": "SSN", "selected": true },
            { "viewValue": "DOB", "selected": false }
          ],
          "frontPassInformation": [],
          "brandLogo": "https://cdn.example.com/brand-logo.png",
          "iconImage": "https://cdn.example.com/icon.png",
          "stripImage": "https://cdn.example.com/strip.png",
          "thumbnailImage": "https://cdn.example.com/thumbnail.png",
          "clientName": "Client X",
          "logo": "https://cdn.example.com/logo.png",
          "notificationLogo": "https://cdn.example.com/notify-logo.png",
          "backgroundColor": "#FFFFFF",
          "labelsColor": "#000000",
          "backPassInformation": [],
          "sectionStatus": "Completed"
        },
        "notificationsOptions": {
          "notificationOptions": [
            {
              "isChecked": "true",
              "notificationType": "Email",
              "defaultNotificationContents": "Default email content",
              "defaultBusinessLogic": "Send if inactive"
            }
          ],
          "userListFile": "users.csv",
          "sectionStatus": "Completed"
        },
        "aciWalletronAgentPortal": {
          "walletronAgentPortal": [
            {
              "name": "John Doe",
              "emailAddress": "john@example.com",
              "role": "Manager"
            }
          ],
          "uploadFile": "agent_portal_users.csv",
          "sectionStatus": "In Progress"
        },
        "aciWalletronDataExchange": {
          "dailyImportFile": [
            {
              "viewValue": "Daily Import File (select one specific source below)",
              "selected": true,
              "children": [
                {
                  "viewValue": "ACI Walletron File (naming convention: {BillerCode}_Walletron_Accounts_YYYYmmdd_HHMMSS.txt File must be PGP encrypted.",
                  "selected": true
                },
                {
                  "viewValue": "ACI Speedpay file",
                  "selected": true,
                  "list": [
                    {
                      "platform": "testing"
                    }
                  ]
                }
              ],
              "indeterminate": false
            }
          ],
          "api": [
            {
              "viewValue": "API (SOAP or REST)",
              "selected": true,
              "children": [
                {
                  "viewValue": "",
                  "selected": true,
                  "list": [
                    {
                      "apiDocumentationLocation": "https://api.example.com/docs"
                    },
                    {
                      "apiUsername": "api_user_123"
                    }
                  ]
                }
              ],
              "indeterminate": false
            }
          ],
          "enrollments": [
            {
              "viewValue": "Enrollments",
              "selected": true,
              "children": [
                {
                  "viewValue": "Daily",
                  "selected": true
                },
                {
                  "viewValue": "Weekly",
                  "selected": true
                },
                {
                  "viewValue": "Monthly",
                  "selected": true
                }
              ],
              "indeterminate": false
            }
          ],
          "emailDistributionList": "asdfas",
          "activity": [
            {
              "viewValue": "Activity (will be generated by default",
              "selected": true,
              "children": [
                {
                  "viewValue": "Daily",
                  "selected": true
                },
                {
                  "viewValue": "Weekly",
                  "selected": true
                },
                {
                  "viewValue": "Monthly",
                  "selected": true
                }
              ],
              "indeterminate": false
            }
          ],
          "enrolledAccounts": [
            {
              "viewValue": "Enrolled Accounts",
              "selected": true,
              "children": [
                {
                  "viewValue": "Daily",
                  "selected": true
                },
                {
                  "viewValue": "Weekly",
                  "selected": true
                },
                {
                  "viewValue": "Monthly",
                  "selected": true
                }
              ],
              "indeterminate": false
            }
          ],
          "sftpUrl": "",
          "sftpDirectory": "",
          "inboundFile": "",
          "timeFileSent": "",
          "groupEmailAddress": "",
          "phoneNumber": "",
          "followUpTime": "",
          "pgpEncryptionKey": "",
          "clientPgpEncryptionKey": "",
          "frequency": "",
          "fileTransmissionTime": "",
          "ipAddresses": "",
          "confirmedBy": "",
          "sectionStatus": "completed"
        },
        "aciWalletronEnrollmentStrategy": {
          "websiteOrMobileApp": [
            {
              "strategy": "Login Button",
              "btnPresent": "Yes",
              "additionalAuthPage": "OTP Page"
            }
          ],
          "emailOrStatementQRCode": [
            {
              "channel": "Email",
              "campaign": "Promo2025",
              "oneTimeOrContinuing": "OneTime"
            }
          ],
          "sectionStatus": "Completed"
        },
        "enrollmentUrl": {
          "testUrl": "https://test-enroll.example.com",
          "prodUrl": "https://prod-enroll.example.com",
          "sectionStatus": "Completed"
        },
        "targetedCommunication": {
          "website": [
            {
              "dataPoints": "Login Time",
              "dataType": "Timestamp",
              "options": "Required"
            }
          ],
          "sectionStatus": "In Progress"
        },
        "aciCash": {
          "numberOfAccounts": "333",
          "aciCashPaymentFees": [
            {
              "viewValue": "No Consumer Fee (some states do not allow fees)",
              "selected": false,
              "indeterminate": null,
              "children": null
            },
            {
              "viewValue": "Consumer Fee",
              "selected": true,
              "children": [
                {
                  "viewValue": "",
                  "selected": true,
                  "list": [
                    {
                      "serviceFeeAmount": "10.00"
                    }
                  ]
                }
              ],
              "indeterminate": false
            }
          ],
          "uat": "",
          "prod": "",
          "payItTodayUcp": "",
          "existingD1Client": [
            {
              "viewValue": "Yes",
              "selected": false,
              "indeterminate": null,
              "children": null
            },
            {
              "viewValue": "No",
              "selected": true,
              "children": [
                {
                  "viewValue": "",
                  "selected": true,
                  "list": [
                    {
                      "d1BillerIdFee": "BID123"
                    },
                    {
                      "d1BillerIdNoFee": "BID456"
                    }
                  ]
                }
              ],
              "indeterminate": false
            }
          ],
          "paymentsPlatform": [
            {
              "viewValue": "V4",
              "selected": true,
              "indeterminate": false,
              "children": null
            },
            {
              "viewValue": "Speedpay – NextGen",
              "selected": true,
              "indeterminate": false,
              "children": null
            },
            {
              "viewValue": "Speedpay One",
              "selected": true,
              "indeterminate": false,
              "children": null
            },
            {
              "viewValue": "Other",
              "selected": true,
              "children": [
                {
                  "viewValue": "",
                  "selected": true,
                  "list": [
                    {
                      "otherPaymentsPlatform": "Custom Platform"
                    }
                  ]
                }
              ],
              "indeterminate": false
            }
          ],
          "realTimePaymentsPosting": [
            {
              "viewValue": "Existing",
              "selected": false,
              "indeterminate": null,
              "children": null
            },
            {
              "viewValue": "Create New",
              "selected": true,
              "children": [
                {
                  "viewValue": "",
                  "selected": true,
                  "list": [
                    {
                      "rtpUrl": "https://rtp.example.com"
                    },
                    {
                      "rtpCredentials": "rtp_creds_123"
                    }
                  ]
                }
              ],
              "indeterminate": false
            },
            {
              "viewValue": "RTP Via E-mail (provide email)",
              "selected": false,
              "indeterminate": null,
              "children": null
            },
            {
              "viewValue": "No RTP",
              "selected": false,
              "indeterminate": null,
              "children": null
            },
            {
              "viewValue": "Other",
              "selected": true,
              "children": [
                {
                  "viewValue": "",
                  "selected": true,
                  "list": [
                    {
                      "otherPaymentPosting": "Custom RTP"
                    }
                  ]
                }
              ],
              "indeterminate": false
            }
          ],
          "accountLookUp": [
            {
              "viewValue": "MAM File",
              "selected": true,
              "children": [
                {
                  "viewValue": "Existing",
                  "selected": true
                },
                {
                  "viewValue": "New",
                  "selected": true
                }
              ],
              "indeterminate": false
            },
            {
              "viewValue": "Real-time via API",
              "selected": true,
              "children": [
                {
                  "viewValue": "Existing",
                  "selected": true
                },
                {
                  "viewValue": "New",
                  "selected": true
                }
              ],
              "indeterminate": false
            }
          ],
          "aciCashBarcodeDistribution": [
            {
              "viewValue": "ACI Walletron",
              "selected": true,
              "indeterminate": false
            },
            {
              "viewValue": "Customer statement / bills (ACI to provide to client via batch or API)",
              "selected": true,
              "indeterminate": false
            }
          ],
          "sectionStatus": "completed"
        },
        "walletronApprovals": {
          "clientRepresentativeNameAndTitle": "Alice Smith, Director",
          "clientRepresentativeSignature": "AliceSignature.png",
          "clientRepresentativeDate": "2025-06-11T12:00:00",
          "aciWorldwideProjectManagerName": "Bob Johnson",
          "aciWorldwideProjectManagerSignature": "BobSignature.png",
          "aciWorldwideProjectManagerDate": "2025-06-11T12:30:00",
          "sectionStatus": "Signed"
        }
      }""";

  public static final String WALLETRON_SUCCESS_RESPONSE =
      "{\n"
          + "  \"status\": \"Successful\",\n"
          + "  \"message\": \"Walletron created successfully\",\n"
          + "  \"data\": "
          + WALLETRON_REQUEST_EXAMPLE
          + ",\n"
          + "  \"errors\": null\n"
          + "}";

  public static final String WALLETRON_VALIDATION_ERROR =
      """
      {
        "status": "failure",
        "message": "Invalid request",
        "data": null,
        "errors": {
          "status": "Invalid status value",
          "brdId": "BRD ID is required"
        }
      }""";

  public static final String WALLETRON_ALREADY_EXISTS =
      """
      {
        "status": "failure",
        "message": "Walletron already exists with BRD ID: BRD-1234",
        "data": null,
        "errors": null
      }""";

  public static final String WALLETRON_INTERNAL_SERVER_ERROR =
      """
      {
        "status": "failure",
        "message": "Something went wrong",
        "data": null,
        "errors": null
      }""";

  public static final String WALLETRON_NOT_FOUND =
      """
      {
        "status": "failure",
        "message": "Walletron not found with BRD ID: BRD-9999",
        "data": null,
        "errors": null
      }""";

  public static final String WALLETRON_FORBIDDEN_ERROR =
      """
      {
        "status": "failure",
        "message": "Access denied. You do not have permission to perform this action",
        "data": null,
        "errors": null
      }""";

  // WalletronUsers JSON Request/Response Examples
  public static final String WALLETRON_USERS_JSON_REQUEST =
      """
      {
        "walletronId": "WAL-001",
        "brdId": "BRD-001",
        "users": [
          {
            "name": "John Doe",
            "email": "john.doe@example.com",
            "role": "USER"
          },
          {
            "name": "Jane Smith",
            "email": "jane.smith@example.com",
            "role": "ADMIN"
          },
          {
            "name": "Bob Johnson",
            "email": "bob.johnson@example.com",
            "role": "MANAGER"
          }
        ]
      }""";

  public static final String WALLETRON_USERS_SUCCESS_RESPONSE =
      """
      {
        "status": "SUCCESS",
        "message": "WalletronUsers processed successfully",
        "data": {
          "savedUsers": [
            {
              "id": "64f7a1b2c3d4e5f6a7b8c9d0",
              "name": "John Doe",
              "email": "john.doe@example.com",
              "role": "USER",
              "walletronId": "WAL-001",
              "brdId": "BRD-001",
              "createdAt": "2025-06-18T10:30:00"
            },
            {
              "id": "64f7a1b2c3d4e5f6a7b8c9d1",
              "name": "Bob Johnson",
              "email": "bob.johnson@example.com",
              "role": "MANAGER",
              "walletronId": "WAL-001",
              "brdId": "BRD-001",
              "createdAt": "2025-06-18T10:30:00"
            }
          ],
          "duplicateEmails": ["jane.smith@example.com"],
          "totalProcessed": 3,
          "totalDuplicates": 1
        },
        "errors": null
      }""";

  // File Upload Examples
  public static final String WALLETRON_USERS_CSV_FILE_FORMAT =
      """
      name,email,role
      John Doe,john.doe@example.com,USER
      Jane Smith,jane.smith@example.com,ADMIN
      Bob Johnson,bob.johnson@example.com,MANAGER
      Alice Brown,alice.brown@example.com,PM
      Charlie Wilson,charlie.wilson@example.com,BA
      Diana Davis,diana.davis@example.com,BILLER""";

  public static final String WALLETRON_USERS_FILE_UPLOAD_SUCCESS_RESPONSE =
      """
      {
        "status": "SUCCESS",
        "message": "WalletronUsers processed successfully",
        "data": {
          "savedUsers": [
            {
              "id": "64f7a1b2c3d4e5f6a7b8c9d0",
              "name": "John Doe",
              "email": "john.doe@example.com",
              "role": "USER",
              "walletronId": "WAL-002",
              "brdId": "BRD-002",
              "createdAt": "2025-06-18T11:15:00"
            },
            {
              "id": "64f7a1b2c3d4e5f6a7b8c9d1",
              "name": "Jane Smith",
              "email": "jane.smith@example.com",
              "role": "ADMIN",
              "walletronId": "WAL-002",
              "brdId": "BRD-002",
              "createdAt": "2025-06-18T11:15:00"
            },
            {
              "id": "64f7a1b2c3d4e5f6a7b8c9d2",
              "name": "Bob Johnson",
              "email": "bob.johnson@example.com",
              "role": "MANAGER",
              "walletronId": "WAL-002",
              "brdId": "BRD-002",
              "createdAt": "2025-06-18T11:15:00"
            }
          ],
          "duplicateEmails": [],
          "totalProcessed": 6,
          "totalDuplicates": 0
        },
        "errors": null
      }""";

  // Error Response Examples
  public static final String WALLETRON_USERS_VALIDATION_ERROR =
      """
      {
        "status": "failure",
        "message": "Users list cannot be empty",
        "data": {
          "timestamp": "2025-06-18T10:30:00",
          "status": 400,
          "error": "Bad Request",
          "message": "Users list cannot be empty"
        },
        "errors": null
      }""";

  public static final String WALLETRON_USERS_INVALID_EMAIL_ERROR =
      """
      {
        "status": "failure",
        "message": "users[0].email: Email should be valid",
        "data": {
          "timestamp": "2025-06-18T10:30:00",
          "status": 400,
          "error": "Bad Request",
          "message": "users[0].email: Email should be valid"
        },
        "errors": null
      }""";

  public static final String WALLETRON_USERS_MISSING_REQUIRED_FIELD_ERROR =
      """
      {
        "status": "failure",
        "message": "users[1].name: Name cannot be null",
        "data": {
          "timestamp": "2025-06-18T10:30:00",
          "status": 400,
          "error": "Bad Request",
          "message": "users[1].name: Name cannot be null"
        },
        "errors": null
      }""";

  public static final String WALLETRON_USERS_FILE_TOO_LARGE_ERROR =
      """
      {
        "status": "failure",
        "message": "File size 3145728 bytes exceeds maximum allowed size of 2097152 bytes (2MB)",
        "data": {
          "timestamp": "2025-06-18T10:30:00",
          "status": 400,
          "error": "Bad Request",
          "message": "File size 3145728 bytes exceeds maximum allowed size of 2097152 bytes (2MB)"
        },
        "errors": null
      }""";

  public static final String WALLETRON_USERS_MISSING_HEADERS_ERROR =
      """
      {
        "status": "failure",
        "message": "Missing required headers. Expected: [name, email, role], Found: [Name, Email], Missing: [role]",
        "data": {
          "timestamp": "2025-06-18T10:30:00",
          "status": 400,
          "error": "Bad Request",
          "message": "Missing required headers. Expected: [name, email, role], Found: [Name, Email], Missing: [role]"
        },
        "errors": null
      }""";

  public static final String WALLETRON_USERS_UNSUPPORTED_FILE_FORMAT_ERROR =
      """
      {
        "status": "failure",
        "message": "Unsupported file format. Only CSV and XLSX files are supported.",
        "data": {
          "timestamp": "2025-06-18T10:30:00",
          "status": 400,
          "error": "Bad Request",
          "message": "Unsupported file format. Only CSV and XLSX files are supported."
        },
        "errors": null
      }""";

  public static final String WALLETRON_USERS_FORBIDDEN_ERROR =
      """
      {
        "status": "ERROR",
        "message": "Only Project Managers (PM) can create Walletron users",
        "data": null,
        "errors": null
      }""";

  public static final String WALLETRON_USERS_INTERNAL_SERVER_ERROR =
      """
      {
        "status": "ERROR",
        "message": "Internal server error occurred",
        "data": null,
        "error": {
          "error": "Something went wrong: Database connection failed"
        }
      }
      """;

  public static final String WALLETRON_USERS_ALL_EXIST_ERROR =
      """
      {
        "status": "ERROR",
        "message": "All user details already exist in the system for this walletronId",
        "data": null,
        "error": null
      }
      """;

  public static final String STATUS_KEY = "status";

  public static final Set<String> allowedFields =
      Set.of(
          "brdId",
          "brdName",
          "walletronEnabled",
          "siteConfiguration",
          "notificationsOptions",
          "aciWalletronAgentPortal",
          "aciWalletronDataExchange",
          "aciWalletronEnrollmentStrategy",
          "enrollmentUrls",
          "targetedCommunication",
          "aciCash",
          "approvals");
}
